### ISSUE TITLE
Populating the readme

### ISSUE THREAD

**Issue by bcjaeger** [BrianNathanWhite/OpenLong#3]
We should include some basic info in the readme

1. What's the goal of the R package
2. Who is it for?
3. What cohorts will be included?
4. What format are the data provided in, and why?
5. Once we have more code, an example showing how to load and use the data would also be a great addition

**Comment by bcjaeger** [comment]
@simar7511, would you be willing to work on this issue? Here are steps you could take to complete it:


1.	If you haven't already forked and cloned `OpenLong`, run 1usethis::create_from_github(“BrianNathanWhite/OpenLong”, destdir = “path/to/your/projects”)` in your R console to fork and clone `OpenLong`.
1.	Create a new branch, preferably call it “issue3” since this is issue # 3. 
1.	Fill in the readme with a first draft, answering the questions I wrote in the issue.  
1.	Knit the readme and update your work until you’re happy with it.
1.	Commit the modifications of the readme to your branch
1.	Push your branch to your fork of OpenLong, e.g., `git push -u origin issue3`
1.	Navigate to your forked repo branch and open a PR
1.	Request my review on the PR

**Comment by BrianNathanWhite** [comment]
@bcjaeger I can take care of this is Simar is busy with other things.

**Comment by bcjaeger** [comment]
All yours =]
