### ISSUE TITLE
gitignore template for R packages

### ISSUE THREAD

**Issue by bcjaeger** [BrianNathanWhite/OpenLong#4]
We ought to make our `.gitignore` file a little more geared for R packages. Copying the template here would be a great start: https://github.com/github/gitignore/blob/main/R.gitignore

**Comment by bcjaeger** [comment]
@BrianNathanWhite, this may be a good issue for you to check out. If you already know .gitignore and regex it should only take a few minutes, and if you don't know those things it will be a great learning opportunity. Would you be willing to give it a shot?

Here's what "complete" would look like: A pull request is submitted with the `.gitignore` file from the link above replacing the `.gitignore` file we have now. You could also add some extra lines if you think of anything that would be helpful to ignore (maybe something in `data-raw`?

**Comment by BrianNathanWhite** [comment]
@bcjaeger Sure, I'll take a stab at this!

**Comment by BrianNathanWhite** [comment]
So I modified the .gitignore file locally and added a line for it to ignore the /sensitive/ sub-folder within the data-raw directory. How do I submit a pull request from R studio given that the local version is the master branch?

**Comment by bcjaeger** [comment]
🍾 🥳
